name: NoCa CI

# Run tests on any push or pullRequest event
on: [push, pull_request]

jobs:
  maya:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maya-version: [2016, 2018]
    container: docker://mottosso/maya:${{ matrix.version }}
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run Tests
      run: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v     
