name: NoCa CI

# Run tests on any push or pullRequest event
on: [push, pull_request]

jobs:
  test_maya:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Load Docker Image
      uses: docker://mottosso/maya:2018
      with:
        args: |
          /bin/sh -c "cd /usr/autodesk/maya && ls -la"    # access folder and list the files
          
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
