name: NoCa CI

# Run tests on any push or pullRequest event
on: [push, pull_request]

jobs:
  maya2017:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Load Docker Image
      uses: docker://mottosso/maya:2017
      with:
        args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v
         
  maya2018:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Load Docker Image
      uses: docker://mottosso/maya:2018
      with:
        args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v
         
  maya2019:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Load Docker Image
      uses: docker://mottosso/maya:2019
      with:
        args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v
         
  maya2020:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Load Docker Image
      uses: docker://mottosso/maya:2020
      with:
        args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v
