name: NoCa CI

# Run tests on any push or pullRequest event
on: [push, pull_request]

jobs:
  test_maya:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Load Docker Image
      uses: docker://mottosso/maya:2018
      with:
        args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v
         
